# Gunakan image node
FROM node:22

# Set working directory
WORKDIR /app

# Copy package.json dan package-lock.json & Install dependencies
COPY package*.json ./
RUN npm install 

# Copy source code
COPY . .

# Expose port
EXPOSE 8000

# Run command
RUN chmod +x start.sh

# Use start.sh
CMD ["./start.sh"]

# CMD ["npm", "app.js"]